### ISSUE TITLE
Problem with routing pathname and browserHistory

### ISSUE THREAD

**Issue by ekeric13** [rackt/react-router-redux#261]
I am working with an app that has a default pathname of '/something/' after the hostname. 
When using browserHistory I have to do:
```js
<Provider store={store}>
  <Router history={ browserHistory }>
    <Route path="/something/" component={App}>
       <Route path="main" component={Main} />
       <Route path="*" component={NotFound}/>
    </Route>
  </Router>
</Provider>
```

And then when I want to go to a new route I need to do
`onClick={() => dispatch(routeActions.push('/something/main'))`

And the catch all path for the NotFound component doesn't even work. This is the main problem I am having.

Yet when I use hash history it works how you think it would:

```js
<Provider store={store}>
  <Router history={ hashHistory }>
    <Route path="/" component={App}>
       <Route path="main" component={Main} />
       <Route path="*" component={NotFound}/>
    </Route>
  </Router>
</Provider>
```

`onClick={() => dispatch(routeActions.push('/main'))`

Yet it seems that you recommend using browserHistory . ["Browser history is the recommended history for browser application with React Router."](https://github.com/rackt/react-router/blob/latest/docs/guides/basics/Histories.md)

What makes browserHistory better? And is there a way I can get browserHistory working that isn't so buggy and allows me to use the catch all path given the default pathname is `/something` and not `/`?

**Comment by timdorr** [comment]
Did you mean to post this on the main react-router repo? This isn't specific to react-router-redux.

And before you post an issue there, we don't accept questions on that repo. Instead, your best bet is to post on Stack Overflow or Reactiflux, where you'll have more eyeballs on your question. I would specify what you mean by "the NotFound component doesn't even work". You should add whatever happens at that point because how it fails would be key to solving the issue.

**Comment by ekeric13** [comment]
I thought this dealt with react-router-redux since I was having to prepend the dispatch push actions with `/something`. Posting this on reactiflux seems like a great suggestion and I will post additional info about how the NotFound component fails like you said. Thanks!
